import {
  Analytics01Icon,
  Atom01Icon,
  Award01Icon,
  BoltIcon,
  BookOpen01Icon,
  BrainIcon,
  BugIcon,
  CameraIcon,
  CloudIcon,
  CodeIcon,
  CoffeeIcon,
  ComputerTerminal01Icon,
  CpuIcon,
  CrownIcon,
  DatabaseIcon,
  DiamondIcon,
  FilmIcon,
  FireIcon,
  FlaskConicalIcon,
  GameController01Icon,
  GitBranchIcon,
  Globe02Icon,
  HeartIcon,
  Home01Icon,
  LeafIcon,
  MagicWand01Icon,
  MusicNoteIcon,
  Package01Icon,
  Pen01Icon,
  RocketIcon,
  ServerStackIcon,
  ShieldIcon,
  StarIcon,
  TerminalIcon,
} from "@hugeicons/core-free-icons";

export const WORKSPACE_ICON_PALETTE = [
  { name: "CodeIcon", label: "Code", icon: CodeIcon },
  { name: "TerminalIcon", label: "Terminal", icon: TerminalIcon },
  { name: "ComputerTerminal01Icon", label: "Console", icon: ComputerTerminal01Icon },
  { name: "DatabaseIcon", label: "Database", icon: DatabaseIcon },
  { name: "CpuIcon", label: "CPU", icon: CpuIcon },
  { name: "GitBranchIcon", label: "Git", icon: GitBranchIcon },
  { name: "ServerStackIcon", label: "Server", icon: ServerStackIcon },
  { name: "BugIcon", label: "Debug", icon: BugIcon },
  { name: "FlaskConicalIcon", label: "Testing", icon: FlaskConicalIcon },
  { name: "Package01Icon", label: "Package", icon: Package01Icon },
  { name: "BookOpen01Icon", label: "Docs", icon: BookOpen01Icon },
  { name: "MagicWand01Icon", label: "Design", icon: MagicWand01Icon },
  { name: "Pen01Icon", label: "Write", icon: Pen01Icon },
  { name: "CameraIcon", label: "Camera", icon: CameraIcon },
  { name: "MusicNoteIcon", label: "Music", icon: MusicNoteIcon },
  { name: "GameController01Icon", label: "Game", icon: GameController01Icon },
  { name: "FilmIcon", label: "Film", icon: FilmIcon },
  { name: "Atom01Icon", label: "Science", icon: Atom01Icon },
  { name: "StarIcon", label: "Star", icon: StarIcon },
  { name: "HeartIcon", label: "Heart", icon: HeartIcon },
  { name: "RocketIcon", label: "Rocket", icon: RocketIcon },
  { name: "FireIcon", label: "Fire", icon: FireIcon },
  { name: "CrownIcon", label: "Crown", icon: CrownIcon },
  { name: "DiamondIcon", label: "Diamond", icon: DiamondIcon },
  { name: "BoltIcon", label: "Bolt", icon: BoltIcon },
  { name: "Award01Icon", label: "Award", icon: Award01Icon },
  { name: "Home01Icon", label: "Home", icon: Home01Icon },
  { name: "Globe02Icon", label: "Web", icon: Globe02Icon },
  { name: "CloudIcon", label: "Cloud", icon: CloudIcon },
  { name: "BrainIcon", label: "AI", icon: BrainIcon },
  { name: "LeafIcon", label: "Eco", icon: LeafIcon },
  { name: "CoffeeIcon", label: "Coffee", icon: CoffeeIcon },
  { name: "Analytics01Icon", label: "Analytics", icon: Analytics01Icon },
  { name: "ShieldIcon", label: "Security", icon: ShieldIcon },
] as const;

export type WorkspaceIconName = (typeof WORKSPACE_ICON_PALETTE)[number]["name"];

export function getWorkspaceIcon(name: string) {
  return WORKSPACE_ICON_PALETTE.find((e) => e.name === name)?.icon ?? null;
}
