/** Frontend mirror of the Rust editor catalog — id/name pairs only. */
export const EDITOR_CATALOG: { id: string; name: string }[] = [
  { id: "vscode", name: "VS Code" },
  { id: "vscode-insiders", name: "VS Code Insiders" },
  { id: "vscodium", name: "VSCodium" },
  { id: "cursor", name: "Cursor" },
  { id: "windsurf", name: "Windsurf" },
  { id: "zed", name: "Zed" },
  { id: "zed-preview", name: "Zed Preview" },
  { id: "kiro", name: "Kiro" },
  { id: "trae", name: "Trae" },
  { id: "antigravity", name: "Antigravity" },
  { id: "sublime-text", name: "Sublime Text" },
  { id: "atom", name: "Atom" },
  { id: "bbedit", name: "BBEdit" },
  { id: "cotedit", name: "CotEditor" },
  { id: "textmate", name: "TextMate" },
  { id: "coderunner", name: "CodeRunner" },
  { id: "intellij", name: "IntelliJ IDEA" },
  { id: "pycharm", name: "PyCharm" },
  { id: "webstorm", name: "WebStorm" },
  { id: "goland", name: "GoLand" },
  { id: "rubymine", name: "RubyMine" },
  { id: "rustrover", name: "RustRover" },
  { id: "android-studio", name: "Android Studio" },
  { id: "rider", name: "Rider" },
  { id: "appcode", name: "AppCode" },
  { id: "clion", name: "CLion" },
  { id: "phpstorm", name: "PhpStorm" },
  { id: "mps", name: "MPS" },
];
